/** Token counts from an AI agent run */
export interface TokenCounts {
  /** Number of input tokens sent to the model */
  inputTokens: number;
  /** Number of output tokens generated by the model */
  outputTokens: number;
  /** Number of tokens read from the prompt cache */
  cacheReadTokens: number;
  /** Number of tokens written to the prompt cache */
  cacheWriteTokens: number;
}

/** Token counts with a data quality flag */
export interface TokenCountsWithMeta extends TokenCounts {
  /** True if the token data was extracted approximately (e.g. via regex) rather than from structured JSON */
  isApproximate: boolean;
}

/** Parsed inputs from the GitHub Action */
export interface ActionInputs {
  /** AgentMeter API key */
  apiKey: string;
  /** AI engine (claude, copilot, codex) */
  engine: string;
  /** Model identifier, or null if not provided */
  model: string | null;
  /** Raw stdout from the agent step, for JSON/text token extraction */
  agentOutput: string;
  /** Explicit input token count override */
  inputTokens: number | null;
  /** Explicit output token count override */
  outputTokens: number | null;
  /** Explicit cache read token count override */
  cacheReadTokens: number | null;
  /** Explicit cache write token count override */
  cacheWriteTokens: number | null;
  /** Number of agent turns */
  turns: number | null;
  /** Run status */
  status: string;
  /** PR number created by this run */
  prNumber: number | null;
  /** AgentMeter API base URL */
  apiUrl: string;
  /** Whether to post a cost comment on the PR/issue */
  postComment: boolean;
  /** Optional override for trigger number (for workflow_run callers) */
  triggerNumber: number | null;
  /** Optional override for the originating event name (for workflow_run callers) */
  triggerEvent: string;
  /** ISO 8601 start timestamp override (for workflow_run callers) */
  startedAt: string;
  /** ISO 8601 completed timestamp override (for workflow_run callers) */
  completedAt: string;
  /** Run ID of the triggering agent workflow — enables automatic token/trigger/timestamp resolution */
  workflowRunId: number | null;
}

/** Extracted GitHub Actions context */
export interface ActionContext {
  /** GitHub Actions run ID */
  runId: number;
  /** Repository full name (owner/repo) */
  repoFullName: string;
  /** Repository owner */
  owner: string;
  /** Repository name */
  repo: string;
  /** Workflow name */
  workflowName: string;
  /** Trigger type (issue_labeled, pr_comment, etc.) */
  triggerType: string;
  /** Trigger reference (e.g. "#45", "PR #38") */
  triggerRef: string | null;
  /** Numeric trigger reference (issue or PR number) */
  triggerNumber: number | null;
}

/** Payload sent to the AgentMeter ingest API */
export interface IngestPayload {
  /** GitHub Actions run ID */
  githubRunId: number;
  /** Repository full name */
  repoFullName: string;
  /** Workflow name */
  workflowName: string;
  /** Trigger type */
  triggerType: string;
  /** Trigger reference string */
  triggerRef: string | null;
  /** Numeric trigger reference */
  triggerNumber: number | null;
  /** AI engine identifier */
  engine: string;
  /** Model identifier */
  model: string | null;
  /** Run status */
  status: string;
  /** PR number created by this run */
  prNumber: number | null;
  /** Run duration in seconds */
  durationSeconds: number | null;
  /** Number of agent turns */
  turns: number | null;
  /** ISO 8601 start time */
  startedAt: string;
  /** ISO 8601 end time */
  completedAt: string;
  /** Token usage data */
  tokens?: TokenCountsWithMeta;
}

/** Response from the AgentMeter ingest API */
export interface IngestResponse {
  /** AgentMeter run UUID */
  id: string;
  /** Total cost in integer cents */
  totalCostCents: number;
  /** Link to the run in the dashboard */
  dashboardUrl: string;
}

/** Data for a single run row in the PR comment */
export interface RunCommentData {
  /** Workflow name */
  workflowName: string;
  /** Run status */
  status: string;
  /** Total cost in cents */
  totalCostCents: number;
  /** Token counts, if available */
  tokens?: TokenCountsWithMeta;
  /** Model identifier */
  model: string | null;
  /** Number of agent turns */
  turns: number | null;
  /** Run duration in seconds */
  durationSeconds: number | null;
  /** Link to the run in the dashboard */
  dashboardUrl: string;
}

/** Token data written to agent-tokens.json artifact by gh-aw compiled workflows */
export interface AgentTokensArtifact {
  /** Input tokens used */
  input_tokens: number;
  /** Output tokens used */
  output_tokens: number;
  /** Cache read tokens */
  cache_read_tokens: number;
  /** Cache write tokens */
  cache_write_tokens: number;
}

/**
 * A single JSONL event emitted by `codex exec` in streaming mode.
 * Token counts are found in `token_count` events.
 * Written to the rollout JSONL file at `$CODEX_HOME/sessions/YYYY/MM/DD/rollout-*.jsonl`.
 */
export interface CodexTokenEvent {
  type: 'event_msg';
  payload: {
    type: 'token_count';
    info: {
      total_token_usage: {
        /** Total input tokens (does not include cached) */
        input_tokens?: number;
        /** Total output tokens */
        output_tokens?: number;
        /** Tokens served from the prompt cache */
        cached_input_tokens?: number;
      };
    };
  };
}

/**
 * A `turn.completed` event emitted to stdout when running `codex exec --json`.
 * Sums all turns for total usage of a full `codex exec` run.
 */
export interface CodexExecTurnCompleted {
  type: 'turn.completed';
  usage: {
    /** Total input tokens sent (includes cached) */
    input_tokens?: number;
    /** Output tokens generated */
    output_tokens?: number;
    /** Input tokens served from cache (subset of input_tokens) */
    cached_input_tokens?: number;
  };
}

/** Known Claude Code JSON output structure (best-effort) */
export interface ClaudeCodeOutput {
  /** Top-level usage block */
  usage?: {
    input_tokens?: number;
    output_tokens?: number;
    cache_read_input_tokens?: number;
    cache_creation_input_tokens?: number;
  };
  /** Some versions nest usage under result */
  result?: {
    usage?: {
      input_tokens?: number;
      output_tokens?: number;
      cache_read_input_tokens?: number;
      cache_creation_input_tokens?: number;
    };
  };
  /** Some versions include cost_usd directly */
  cost_usd?: number;
}
