/** Token counts from an AI agent run */
export interface TokenCounts {
  /** Number of input tokens sent to the model */
  inputTokens: number;
  /** Number of output tokens generated by the model */
  outputTokens: number;
  /** Number of tokens read from the prompt cache */
  cacheReadTokens: number;
  /** Number of tokens written to the prompt cache */
  cacheWriteTokens: number;
}

/** Token counts with a data quality flag */
export interface TokenCountsWithMeta extends TokenCounts {
  /** True if the token data was extracted approximately (e.g. via regex) rather than from structured JSON */
  isApproximate: boolean;
}

/** Parsed inputs from the GitHub Action */
export interface ActionInputs {
  /** AgentMeter API key */
  apiKey: string;
  /** AI engine (claude, copilot, codex) */
  engine: string;
  /** Model identifier, or null if not provided */
  model: string | null;
  /** Raw stdout from the agent step, for JSON/text token extraction */
  agentOutput: string;
  /** Explicit input token count override */
  inputTokens: number | null;
  /** Explicit output token count override */
  outputTokens: number | null;
  /** Explicit cache read token count override */
  cacheReadTokens: number | null;
  /** Explicit cache write token count override */
  cacheWriteTokens: number | null;
  /** Number of agent turns */
  turns: number | null;
  /** Run status */
  status: string;
  /** PR number created by this run */
  prNumber: number | null;
  /** AgentMeter API base URL */
  apiUrl: string;
  /** Whether to post a cost comment on the PR/issue */
  postComment: boolean;
}

/** Extracted GitHub Actions context */
export interface ActionContext {
  /** GitHub Actions run ID */
  runId: number;
  /** Repository full name (owner/repo) */
  repoFullName: string;
  /** Repository owner */
  owner: string;
  /** Repository name */
  repo: string;
  /** Workflow name */
  workflowName: string;
  /** Trigger type (issue_labeled, pr_comment, etc.) */
  triggerType: string;
  /** Trigger reference (e.g. "#45", "PR #38") */
  triggerRef: string | null;
  /** Numeric trigger reference (issue or PR number) */
  triggerNumber: number | null;
}

/** Payload sent to the AgentMeter ingest API */
export interface IngestPayload {
  /** GitHub Actions run ID */
  githubRunId: number;
  /** Repository full name */
  repoFullName: string;
  /** Workflow name */
  workflowName: string;
  /** Trigger type */
  triggerType: string;
  /** Trigger reference string */
  triggerRef: string | null;
  /** Numeric trigger reference */
  triggerNumber: number | null;
  /** AI engine identifier */
  engine: string;
  /** Model identifier */
  model: string | null;
  /** Run status */
  status: string;
  /** PR number created by this run */
  prNumber: number | null;
  /** Run duration in seconds */
  durationSeconds: number | null;
  /** Number of agent turns */
  turns: number | null;
  /** ISO 8601 start time */
  startedAt: string;
  /** ISO 8601 end time */
  completedAt: string;
  /** Token usage data */
  tokens?: TokenCountsWithMeta;
}

/** Response from the AgentMeter ingest API */
export interface IngestResponse {
  /** AgentMeter run UUID */
  id: string;
  /** Total cost in integer cents */
  totalCostCents: number;
  /** Link to the run in the dashboard */
  dashboardUrl: string;
}

/** Data for a single run row in the PR comment */
export interface RunCommentData {
  /** Workflow name */
  workflowName: string;
  /** Run status */
  status: string;
  /** Total cost in cents */
  totalCostCents: number;
  /** Token counts, if available */
  tokens?: TokenCountsWithMeta;
  /** Model identifier */
  model: string | null;
  /** Number of agent turns */
  turns: number | null;
  /** Link to the run in the dashboard */
  dashboardUrl: string;
}

/** Known Claude Code JSON output structure (best-effort) */
export interface ClaudeCodeOutput {
  /** Top-level usage block */
  usage?: {
    input_tokens?: number;
    output_tokens?: number;
    cache_read_input_tokens?: number;
    cache_creation_input_tokens?: number;
  };
  /** Some versions nest usage under result */
  result?: {
    usage?: {
      input_tokens?: number;
      output_tokens?: number;
      cache_read_input_tokens?: number;
      cache_creation_input_tokens?: number;
    };
  };
  /** Some versions include cost_usd directly */
  cost_usd?: number;
}
